-- create the ELEMENT table

CREATE TABLE ELEMENT (
	ELEMENT_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(64) NOT NULL,
    DESCRIPTION VARCHAR(255),
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- Add the CRI score types to the table
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (1,'QUALITY');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (2,'AVAILABILITY');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (3,'SATISFACTION');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (4,'SCHEDULE');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (5,'REQUIREMENTS');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) 
    VALUES (6,'OVERALL');


-- create the overall score table
CREATE TABLE CRI_SCORE (
	CRI_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	ELEMENT_ID NUMBER(10,0) NOT NULL FOREIGN KEY 
	    REFERENCES ELEMENT(ELEMENT_Id),
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- remove ELEMENT table
--DROP TABLE ELEMENT;
--DROP TABLE CRI_SCORE;
