-- create the raw data tables

CREATE TABLE QUALITY_RAW (
	QUALITY_RAW_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	DEV_EFFORT NUMBER(10,0) NOT NULL,
	TEST_EFFORT NUMBER(10,0),
	SIT_DEFECTS NUMBER(10,0),
	UAT_DEFECTS NUMBER(10,0),
	PROD_DEFECTS NUMBER(10,0) NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE AVAILABILITY_RAW (
	AVAILABILITY_RAW_ID RAW(16) NOT NULL PRIMARY KEY,
	SERVICE_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	UPTIME NUMBER(10,5),
	SCHED_DOWNTIME NUMBER(10,5),
	UNSCHED_DOWNTIME NUMBER(10,5),
	PERCENT_UPTIME NUMBER(10,5) NOT NULL,
	EXPECT_PERCENT_UPTIME NUMBER(10,5) NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SATISFACTION_RAW (
	SATISFACTION_RAW_ID RAW(16) NOT NULL PRIMARY KEY,
	QUESTION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	QUESTION_TEXT VARCHAR2(1024),
	RESPONDENT_ID VARCHAR2(128),
	RESPONSE NUMBER(5,0) NOT NULL,
	RESPONSE_DATE DATE,
	APPLICATION_ID VARCHAR2(64),
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SCHEDULE_RAW (
	SCHEDULE_RAW_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64),
	FREQ_DATE DATE NOT NULL,
	SCHED_START_DATE DATE NOT NULL,
	SCHED_FINISH_DATE DATE NOT NULL,
	ACTUAL_START_DATE DATE,
	ACTUAL_FINISH_DATE DATE NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE REQUIREMENTS_RAW (
	REQUIREMENTS_RAW_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64),
	FREQ_DATE DATE NOT NULL,
	SCHED_REQ NUMBER(10,0) NOT NULL,
	ACTUAL_REQ NUMBER(10,0) NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- remove the raw tables
DROP TABLE QUALITY_RAW;
DROP TABLE AVAILABILITY_RAW;
DROP TABLE SATISFACTION_RAW;
DROP TABLE SCHEDULE_RAW;
DROP TABLE REQUIREMENTS_RAW;
