

-- Create the scoring tables

CREATE TABLE QUALITY_SCORE (
	QUALITY_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE AVAILABILITY_SCORE (
	AVAILABILITY_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	SERVICE_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SATISFACTION_SCORE (
	AVAILABILITY_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	QUESTION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE SCHEDULE_SCORE (
	QUALITY_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE REQUIREMENTS_SCORE (
	QUALITY_SCORE_ID RAW(16) NOT NULL PRIMARY KEY,
	APPLICATION_ID VARCHAR2(64) NOT NULL,
	FREQ_DATE DATE NOT NULL,
	SCORE NUMBER(10,5) NOT NULL,
	ACTIVE CHAR DEFAULT 'Y' NOT NULL,
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- remove the scoring tables
DROP TABLE QUALITY_SCORE;
DROP TABLE AVAILABILITY_SCORE;
DROP TABLE SATISFACTION_SCORE;
DROP TABLE SCHEDULE_SCORE;
DROP TABLE REQUIREMENTS_SCORE;

-- create the ELEMENT table
CREATE TABLE ELEMENT (
	ELEMENT_ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(64) NOT NULL,
    DESCRIPTION VARCHAR(255),
	INSERT_DATE DATE DEFAULT SYSDATE NOT NULL,
	UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- Add the MPI score types to the table
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (1,'QUALITY');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (2,'AVAILABILITY');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (3,'SATISFACTION');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (4,'SCHEDULE');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (5,'REQUIREMENTS');
INSERT INTO ELEMENT (ELEMENT_ID,NAME) VALUES (6,'OVERALL');

-- remove ELEMENT table
DROP TABLE ELEMENT;



